#2020.0114.1836 notebn
CUDA_VISIBLE_DEVICES=0 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=1 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr1-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_1sent_10epoch_maxwords510_test_20200114_1831.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=3 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr3-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_3sent_10epoch_maxwords510_test_20200111_1832.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=4 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr4-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_4sent_10epoch_maxwords510_test_20200111_1833.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=5 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr5-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_5sent_10epoch_maxwords510_test_20200111_1834.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=6 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr6-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_6sent_10epoch_maxwords510_test_20200111_1835.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=7 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr7-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_7sent_10epoch_maxwords510_test_20200111_1836.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=10 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr10-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_10sent_10epoch_maxwords510_test_20200111_1837.txt &

#2020.0114.1841 wnut16
CUDA_VISIBLE_DEVICES=1 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=1 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr1-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_1sent_10epoch_maxwords510_test_20200114_1841.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=3 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr3-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_3sent_10epoch_maxwords510_test_20200114_1842.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=4 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr4-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_4sent_10epoch_maxwords510_test_20200114_1843.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=5 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr5-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_5sent_10epoch_maxwords510_test_20200114_1844.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=6 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr6-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_6sent_10epoch_maxwords510_test_20200114_1845.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=7 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr7-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_7sent_10epoch_maxwords510_test_20200114_1846.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=10 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr10-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_10sent_10epoch_maxwords510_test_20200114_1847.txt &

#2020.0114.1841 notebc
CUDA_VISIBLE_DEVICES=1 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=1 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr1-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_1sent_10epoch_maxwords510_test_20200114_1841.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=3 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr3-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_3sent_10epoch_maxwords510_test_20200114_1842.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=4 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr4-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_4sent_10epoch_maxwords510_test_20200114_1843.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=5 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr5-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_5sent_10epoch_maxwords510_test_20200114_1844.txt &
CUDA_VISIBLE_DEVICES=#2020.0114.1836 notebn
CUDA_VISIBLE_DEVICES=0 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=1 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr1-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_1sent_10epoch_maxwords510_test_20200114_1831.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=3 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr3-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_3sent_10epoch_maxwords510_test_20200111_1832.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=4 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr4-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_4sent_10epoch_maxwords510_test_20200111_1833.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=5 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr5-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_5sent_10epoch_maxwords510_test_20200111_1834.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=6 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr6-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_6sent_10epoch_maxwords510_test_20200111_1835.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=7 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr7-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_7sent_10epoch_maxwords510_test_20200111_1836.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --corpus_type=notebn --splitType=num_sentence --value=10 --data_dir=data/notebn/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebn/notebn-numtr10-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebn_10sent_10epoch_maxwords510_test_20200111_1837.txt &

#2020.0114.1841 wnut16
CUDA_VISIBLE_DEVICES=1 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=1 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr1-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_1sent_10epoch_maxwords510_test_20200114_1841.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=3 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr3-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_3sent_10epoch_maxwords510_test_20200114_1842.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=4 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr4-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_4sent_10epoch_maxwords510_test_20200114_1843.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=5 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr5-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_5sent_10epoch_maxwords510_test_20200114_1844.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=6 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr6-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_6sent_10epoch_maxwords510_test_20200114_1845.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=7 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr7-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_7sent_10epoch_maxwords510_test_20200114_1846.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --corpus_type=wnut16 --splitType=num_sentence --value=10 --data_dir=data/wnut16/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/wnut16/wnut16-numtr10-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/wnut16_10sent_10epoch_maxwords510_test_20200114_1847.txt &

#2020.0114.1841 notebc
CUDA_VISIBLE_DEVICES=1 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=1 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr1-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_1sent_10epoch_maxwords510_test_20200114_1841.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=3 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr3-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_3sent_10epoch_maxwords510_test_20200114_1842.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=4 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr4-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_4sent_10epoch_maxwords510_test_20200114_1843.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=5 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr5-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_5sent_10epoch_maxwords510_test_20200114_1844.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=6 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr6-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_6sent_10epoch_maxwords510_test_20200114_1845.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=7 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr7-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_7sent_10epoch_maxwords510_test_20200114_1846.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=10 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr10-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_10sent_10epoch_maxwords510_test_20200114_1847.txt &







5 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=6 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr6-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_6sent_10epoch_maxwords510_test_20200114_1845.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=7 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr7-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_7sent_10epoch_maxwords510_test_20200114_1846.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --corpus_type=notebc --splitType=num_sentence --value=10 --data_dir=data/notebc/ --bert_model=bert-base-cased --task_name=ner --output_dir=output/notebc/notebc-numtr10-maxwords510/ --max_seq_length=510 --do_train --num_train_epochs 10 --do_eval --warmup_proportion=0.4 >logs/notebc_10sent_10epoch_maxwords510_test_20200114_1847.txt &







